import React from 'react';

const LandingPage = () => (
  <div>
    <h1>Landing Page</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget augue condimentum libero hendrerit iaculis. Donec gravida aliquam leo, nec posuere magna egestas id. Nunc auctor malesuada magna blandit sollicitudin. Vivamus volutpat ipsum in molestie faucibus. Sed vestibulum ut sapien in aliquet. Ut eu mattis ex, nec congue ligula. Vestibulum pellentesque quam a eros bibendum, id malesuada nisi interdum. Ut viverra leo vitae nisi mattis dapibus. Sed eu ornare orci, ac porta risus. Phasellus porta vulputate elit ac consectetur. Vestibulum sed ante finibus, ultrices nisl in, commodo nunc. Suspendisse a mauris euismod, mollis tortor eu, vehicula leo. Nunc interdum semper tellus eu dapibus. Etiam sagittis vitae est id condimentum.

Morbi venenatis dui et nibh tempor molestie. Duis vehicula diam felis, non tristique massa facilisis at. Sed eget mauris sed turpis suscipit faucibus a a erat. Vestibulum eu eros nulla. Vestibulum at iaculis justo. Morbi iaculis sapien rhoncus justo pretium, id mattis leo tristique. Vestibulum dapibus sodales enim, at vehicula nunc dictum lacinia. Curabitur nec cursus lacus, non pretium lacus. Nam dui tortor, ultricies quis ex non, luctus dapibus magna. Nullam vestibulum, eros non porttitor commodo, est nibh scelerisque sem, nec bibendum diam lacus non arcu. Sed quis mi non mauris dapibus fringilla. Donec egestas eu enim at porta. Integer in nibh dignissim, iaculis ipsum nec, eleifend urna. Donec ac velit est. Vestibulum at justo laoreet, porta lectus ut, dapibus tellus.

Nunc leo ligula, aliquam sed lectus ut, faucibus ullamcorper urna. Fusce suscipit, leo sit amet aliquam scelerisque, odio eros mattis dui, ac facilisis arcu dolor ut ante. Donec vitae felis at dui congue tristique. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla sit amet tortor justo. Aenean vitae lacinia ligula, vestibulum ornare diam. In sit amet mollis dui. Pellentesque vel leo vel felis eleifend dapibus. Nam tincidunt sit amet ligula sit amet ullamcorper. Fusce a quam nec sapien vulputate sollicitudin id nec ex. Donec in vehicula sapien, eu vestibulum ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In pharetra, orci commodo consequat sagittis, dui mi placerat nisl, ultricies pulvinar neque diam quis ipsum. Sed massa massa, accumsan vel dolor eu, convallis tempor magna. Curabitur sed hendrerit diam, id aliquam ipsum. Ut sollicitudin nisl nunc.

Mauris bibendum aliquam ipsum sit amet maximus. Mauris sit amet magna velit. In nec gravida justo. Phasellus ultricies nisi nec luctus rhoncus. Vestibulum aliquet eleifend arcu et facilisis. Aliquam porttitor sem non augue consequat, ut fermentum lectus maximus. Sed vulputate, diam quis commodo elementum, mauris dui finibus turpis, non lacinia magna velit ut est. Aliquam a orci ut nisl sagittis gravida. Vestibulum rhoncus elit vitae magna mollis, nec scelerisque felis euismod. Sed quis sem nec lacus eleifend porttitor. Donec convallis erat sed arcu elementum, nec ullamcorper tortor porta.

Nunc sollicitudin quis arcu et pretium. Aliquam pharetra, nibh volutpat condimentum scelerisque, arcu risus sagittis libero, in sollicitudin arcu ex quis risus. Praesent vitae arcu ut risus eleifend dignissim non quis ex. Mauris vulputate ligula in turpis pharetra, sit amet laoreet sem ullamcorper. In eu velit id risus imperdiet maximus consequat faucibus turpis. In sed neque vel lectus gravida ultricies sit amet eget ante. Sed tellus elit, consectetur et lacinia sit amet, finibus ut justo. Vestibulum convallis sed ex eu congue. Ut convallis risus vitae leo vulputate, gravida convallis metus pulvinar. Cras mollis pharetra convallis. Phasellus dui eros, pellentesque sed risus id, vestibulum imperdiet orci. Integer ultrices neque at dapibus faucibus. Pellentesque elementum varius posuere. Fusce in consectetur lectus, eget malesuada velit. Donec mattis arcu at massa sagittis, vitae gravida urna sollicitudin. Vestibulum sit amet auctor sem, in lobortis nisi.</p>
  </div>
);

export default LandingPage;
